/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddExpense: typeof import('./src/components/AddExpense.vue')['default']
    AverageDailySpendCard: typeof import('./src/components/AverageDailySpendCard.vue')['default']
    DailySpendCard: typeof import('./src/components/DailySpendCard.vue')['default']
    PercentMonthCompleteCard: typeof import('./src/components/PercentMonthCompleteCard.vue')['default']
    PercentSpentCard: typeof import('./src/components/PercentSpentCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpentCard: typeof import('./src/components/SpentCard.vue')['default']
  }
}
