/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddExpense: typeof import('./src/components/AddExpense.vue')['default']
    AddExpenseOld: typeof import('./src/components/AddExpense-old.vue')['default']
    DailySpendingAverageCard: typeof import('./src/components/DailySpendingAverageCard.vue')['default']
    DailySpendingLimitsCard: typeof import('./src/components/DailySpendingLimitsCard.vue')['default']
    DaysLeftCard: typeof import('./src/components/DaysLeftCard.vue')['default']
    DeleteExpense: typeof import('./src/components/DeleteExpense.vue')['default']
    PercentOfMonthCard: typeof import('./src/components/PercentOfMonthCard.vue')['default']
    PercentSpentCard: typeof import('./src/components/PercentSpentCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetSpendLimit: typeof import('./src/components/SetSpendLimit.vue')['default']
    SpentCard: typeof import('./src/components/SpentCard.vue')['default']
  }
}
